version: "3.7"
services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    env_file:
      - db/database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  webserver:
    build: ./nginx
    container_name: webserver_nginx
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build:
      context: ./web
    container_name: webapp
    command: >
      sh -c "python manage.py migrate && gunicorn untitled5.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./web/untitled5:/code
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
      - cache
  cache:
    container_name: redis_cache
    image: redis:alpine

volumes:
  postgres_data:
